# Generated by Django 6.0.4 on 2026-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default='Draft'),
        ),
    ]
